### ISSUE TITLE
Performancedata in scanresult

### ISSUE THREAD

**Issue by Skeeve** [RUB-NDS/WS-TLS-Scanner#11]
I think it could be helpful to have an optional performancedata property in the scan results.

It should be configurable like the threadpool size requested in #10 

Rough idea:

    "performancedata":{
        "initial queue size":XX,
        "final queue size":XX,
        "time in queue": XX (in seconds),
        "queue entry at": UTC time, 
        "queue left at": UTC time,
        "scan started at": UTC time,
        "scan finished at": UTC time
    }

Maybe some more vital data I do not know of?

**Comment by ic0ns** [comment]
Was added with the last release
