### ISSUE TITLE
pool threads sürzen ab (oder hängen?)

### ISSUE THREAD

**Issue by Skeeve** [RUB-NDS/WS-TLS-Scanner#20]
Wir haben verschiedene domains (Siehe slack) bei denen wir im Log den Start des Scans sehen, aber keinen Eintrag fürs Ende. Außerdem übernimmt der pool-thread keine weiteren Aufgaben mehr.

Aktuell hatten wir 5 Threads die auf diese Art "gestorben" waren.

**Comment by ic0ns** [comment]
this issue is already fixed
