### ISSUE TITLE
Scoring seems dubious

### ISSUE THREAD

**Issue by Skeeve** [RUB-NDS/WS-TLS-Scanner#8]
All checks are green. Score is just 94?

![bildschirmfoto 2018-03-20 um 13 07 56](https://user-images.githubusercontent.com/725404/37653624-d1b2f454-2c3f-11e8-8aa4-746623dea37a.png)

Even the result only shows score 100

```
    [{
      "name": "HTTPS_NO_RESPONSE",
      "hasError": false,
      "errorMessage": null,
      "score": 100,
      "scoreType": "hidden",
      "testDetails": [{
        "placeholder": "HTTPS_RESPONSE",
        "values": [{
          "name": "HOST",
          "value": "siwecos.de"
        }]
      }]
    }, {
      "name": "HTTPS_NOT_SUPPORTED",
      "hasError": false,
      "errorMessage": null,
      "score": 100,
      "scoreType": "hidden",
      "testDetails": [{
        "placeholder": "HTTPS_SUPPORTED",
        "values": [{
          "name": "HOST",
          "value": "siwecos.de"
        }]
      }]
    }, {
      "name": "CERTIFICATE_EXPIRED",
      "hasError": false,
      "errorMessage": null,
      "score": 100,
      "scoreType": "success",
      "testDetails": null
    }, {
      "name": "CERTIFICATE_NOT_VALID_YET",
      "hasError": false,
      "errorMessage": null,
      "score": 100,
      "scoreType": "success",
      "testDetails": null
    }, {
      "name": "CERTIFICATE_NOT_SENT_BY_SERVER",
      "hasError": false,
      "errorMessage": null,
      "score": 100,
      "scoreType": "hidden",
      "testDetails": null
    }, {
      "name": "CERTIFICATE_WEAK_HASH_FUNCTION",
      "hasError": false,
      "errorMessage": null,
      "score": 100,
      "scoreType": "success",
      "testDetails": [{
        "placeholder": "HASH_ALGO",
        "values": [{
          "name": "HASH",
          "value": null
        }, {
          "name": "CERTIFICATE",
          "value": null
        }]
      }]
    }, {
      "name": "CIPHERSUITE_ANON",
      "hasError": false,
      "errorMessage": null,
      "score": 100,
      "scoreType": "success",
      "testDetails": null
    }, {
      "name": "CIPHERSUITE_EXPORT",
      "hasError": false,
      "errorMessage": null,
      "score": 100,
      "scoreType": "success",
      "testDetails": null
    }, {
      "name": "CIPHERSUITE_NULL",
      "hasError": false,
      "errorMessage": null,
      "score": 100,
      "scoreType": "success",
      "testDetails": null
    }, {
      "name": "CIPHERSUITE_RC4",
      "hasError": false,
      "errorMessage": null,
      "score": 100,
      "scoreType": "success",
      "testDetails": null
    }, {
      "name": "CIPHERSUITE_DES",
      "hasError": false,
      "errorMessage": null,
      "score": 100,
      "scoreType": "success",
      "testDetails": null
    }, {
      "name": "SWEET32_VULNERABLE",
      "hasError": false,
      "errorMessage": null,
      "score": 100,
      "scoreType": "success",
      "testDetails": null
    }, {
      "name": "CIPHERSUITEORDER_ENFORCED",
      "hasError": false,
      "errorMessage": null,
      "score": 100,
      "scoreType": "success",
      "testDetails": null
    }, {
      "name": "PROTOCOLVERSION_SSL2",
      "hasError": false,
      "errorMessage": null,
      "score": 100,
      "scoreType": "success",
      "testDetails": null
    }, {
      "name": "PROTOCOLVERSION_SSL3",
      "hasError": false,
      "errorMessage": null,
      "score": 100,
      "scoreType": "success",
      "testDetails": null
    }, {
      "name": "PROTOCOLVERSION_TLS13",
      "hasError": false,
      "errorMessage": null,
      "score": 0,
      "scoreType": "hidden",
      "testDetails": null
    }, {
      "name": "CRIME_VULNERABLE",
      "hasError": false,
      "errorMessage": null,
      "score": 100,
      "scoreType": "success",
      "testDetails": null
    }, {
      "name": "POODLE_VULNERABLE",
      "hasError": false,
      "errorMessage": null,
      "score": 100,
      "scoreType": "success",
      "testDetails": null
    }]
```

**Comment by ic0ns** [comment]
Hey,
I'm pretty confident that this is not the newest version of WS-TLS-Scanner which you are testing with - or you are changing the outputs in the preprocessor step. I have attached the current output of the scanner for siwecos.de
`{
  "name": "TLS",
  "hasError": false,
  "errorMessage": null,
  "score": 100,
  "tests": [
    {
      "name": "HTTPS_NO_RESPONSE",
      "hasError": false,
      "errorMessage": null,
      "score": 100,
      "scoreType": "hidden",
      "testDetails": [
        {
          "placeholder": "HTTPS_RESPONSE",
          "values": [
            {
              "name": "HOST",
              "value": "siwecos.de"
            }
          ]
        }
      ]
    },
    {
      "name": "HTTPS_NOT_SUPPORTED",
      "hasError": false,
      "errorMessage": null,
      "score": 100,
      "scoreType": "hidden",
      "testDetails": [
        {
          "placeholder": "HTTPS_SUPPORTED",
          "values": [
            {
              "name": "HOST",
              "value": "siwecos.de"
            }
          ]
        }
      ]
    },
    {
      "name": "CERTIFICATE_EXPIRED",
      "hasError": false,
      "errorMessage": null,
      "score": 100,
      "scoreType": "success",
      "testDetails": null
    },
    {
      "name": "CERTIFICATE_NOT_VALID_YET",
      "hasError": false,
      "errorMessage": null,
      "score": 100,
      "scoreType": "success",
      "testDetails": null
    },
    {
      "name": "CERTIFICATE_NOT_SENT_BY_SERVER",
      "hasError": false,
      "errorMessage": null,
      "score": 100,
      "scoreType": "hidden",
      "testDetails": null
    },
    {
      "name": "CERTIFICATE_WEAK_HASH_FUNCTION",
      "hasError": false,
      "errorMessage": null,
      "score": 100,
      "scoreType": "success",
      "testDetails": [
        {
          "placeholder": "HASH_ALGO",
          "values": [
            {
              "name": "HASH",
              "value": null
            },
            {
              "name": "CERTIFICATE",
              "value": null
            }
          ]
        }
      ]
    },
    {
      "name": "CIPHERSUITE_ANON",
      "hasError": false,
      "errorMessage": null,
      "score": 100,
      "scoreType": "success",
      "testDetails": null
    },
    {
      "name": "CIPHERSUITE_EXPORT",
      "hasError": false,
      "errorMessage": null,
      "score": 100,
      "scoreType": "success",
      "testDetails": null
    },
    {
      "name": "CIPHERSUITE_NULL",
      "hasError": false,
      "errorMessage": null,
      "score": 100,
      "scoreType": "success",
      "testDetails": null
    },
    {
      "name": "CIPHERSUITE_RC4",
      "hasError": false,
      "errorMessage": null,
      "score": 100,
      "scoreType": "success",
      "testDetails": null
    },
    {
      "name": "CIPHERSUITE_DES",
      "hasError": false,
      "errorMessage": null,
      "score": 100,
      "scoreType": "success",
      "testDetails": null
    },
    {
      "name": "SWEET32_VULNERABLE",
      "hasError": false,
      "errorMessage": null,
      "score": 100,
      "scoreType": "success",
      "testDetails": null
    },
    {
      "name": "CIPHERSUITEORDER_ENFORCED",
      "hasError": false,
      "errorMessage": null,
      "score": 100,
      "scoreType": "success",
      "testDetails": null
    },
    {
      "name": "PROTOCOLVERSION_SSL2",
      "hasError": false,
      "errorMessage": null,
      "score": 100,
      "scoreType": "success",
      "testDetails": null
    },
    {
      "name": "PROTOCOLVERSION_SSL3",
      "hasError": false,
      "errorMessage": null,
      "score": 100,
      "scoreType": "success",
      "testDetails": null
    },
    {
      "name": "PROTOCOLVERSION_TLS13",
      "hasError": false,
      "errorMessage": null,
      "score": 0,
      "scoreType": "hidden",
      "testDetails": null
    },
    {
      "name": "CRIME_VULNERABLE",
      "hasError": false,
      "errorMessage": null,
      "score": 100,
      "scoreType": "success",
      "testDetails": null
    },
    {
      "name": "HEARTBLEED_VULNERABLE",
      "hasError": false,
      "errorMessage": null,
      "score": 100,
      "scoreType": "success",
      "testDetails": null
    },
    {
      "name": "INVALID_CURVE_EPHEMERAL_VULNERABLE",
      "hasError": false,
      "errorMessage": null,
      "score": 100,
      "scoreType": "success",
      "testDetails": null
    },
    {
      "name": "INVALID_CURVE_VULNERABLE",
      "hasError": false,
      "errorMessage": null,
      "score": 100,
      "scoreType": "success",
      "testDetails": null
    },
    {
      "name": "PADDING_ORACLE_VULNERABLE",
      "hasError": false,
      "errorMessage": null,
      "score": 100,
      "scoreType": "success",
      "testDetails": null
    },
    {
      "name": "POODLE_VULNERABLE",
      "hasError": false,
      "errorMessage": null,
      "score": 100,
      "scoreType": "success",
      "testDetails": null
    },
    {
      "name": "TLS_POODLE_VULNERABLE",
      "hasError": false,
      "errorMessage": null,
      "score": 100,
      "scoreType": "success",
      "testDetails": null
    },
    {
      "name": "CVE20162107_VULNERABLE",
      "hasError": false,
      "errorMessage": null,
      "score": 100,
      "scoreType": "success",
      "testDetails": null
    }
  ]
}`

**Comment by Skeeve** [comment]
I took it straight from the database, but will ask Marcel to double check he deployed the correct version: Question from my side: How could I checke the deployed version and how can I verify it's the expected one?

**Comment by Skeeve** [comment]
I know compared the results from just know (taken from the database) with those you posted.

They are identical except for these, which are missing in the database:

```
    {
      "name": "HEARTBLEED_VULNERABLE",
      "hasError": false,
      "errorMessage": null,
      "score": 100,
      "scoreType": "success",
      "testDetails": null
    },
    {
      "name": "INVALID_CURVE_EPHEMERAL_VULNERABLE",
      "hasError": false,
      "errorMessage": null,
      "score": 100,
      "scoreType": "success",
      "testDetails": null
    },
    {
      "name": "INVALID_CURVE_VULNERABLE",
      "hasError": false,
      "errorMessage": null,
      "score": 100,
      "scoreType": "success",
      "testDetails": null
    },
    {
      "name": "PADDING_ORACLE_VULNERABLE",
      "hasError": false,
      "errorMessage": null,
      "score": 100,
      "scoreType": "success",
      "testDetails": null
    },
    {
      "name": "TLS_POODLE_VULNERABLE",
      "hasError": false,
      "errorMessage": null,
      "score": 100,
      "scoreType": "success",
      "testDetails": null
    },
    {
      "name": "CVE20162107_VULNERABLE",
      "hasError": false,
      "errorMessage": null,
      "score": 100,
      "scoreType": "success",
      "testDetails": null
    }
```

**Comment by Skeeve** [comment]
Seems resolved
